### ISSUE TITLE
Initial project setup

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#10]
- [x] Git repo
- [x] Vagrant
- [x] Rails project
- [x] Travis
- [x] Linters/Checkers
- [x] Staging site

**Comment by zarino** [comment]
From the frontend dev perspective – a SCSS pipeline, with bootstrap-sass, would be good.

**Comment by stevenday** [comment]
@zarino, your wish is my command! (That mostly comes built in, but I'll make sure bootstrap sass is available)

**Comment by stevenday** [comment]
All this is done
