### ISSUE TITLE
Adding collaborators to studies

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#100]
From @kimmwest's comments here: https://github.com/mysociety/remit/issues/57#issuecomment-180469790

>  We also need them to add collaborators (by collaborators, I don't mean members of the study team, I mean e.g. ministry of health) - you should have seen that in the data schema? I am open to how this happens but I think it makes sense to add similar buttons to 'add an impact' etc.

We have text fields on the study for storing this data, called `international_collaborators` and `local_collaborators` (as well as a field called `research_team` for the other sort of collaborator), but I hadn't considered how user's would edit these, and it doesn't really fit into quite the same model as the other data @kimmwest describes above. Those are separate pieces of data that get added individually and connected to the study, but these fields are just free text boxes. 

We can easily allow non-admin users to edit these fields too, but it'll look and work a bit differently, which makes me think I've misunderstood the data schema. (I'd assumed a single person would come along and fill this in once, just as some extra data about the project, rather than it being something collaboratively edited by lots of people).

@kimmwest can you give us some examples of what you expect this data to look like? Is a simple text box enough to add it, or are you expecting multiple different people to add/remove collaborators individually over time? How are you then going to use this data? Would you need to be able to filter by all the studies that had collaborated with a particular Ministry of Health for example?

**Comment by stevenday** [comment]
After discussing this in the sprint review call we decided that leaving this as a single text field that's edited is fine - MSF's reporting only needs to know how many studies there are that have reported *some* kind of collaborators.

We also decided that this should live under the same process conceptually as adding "impact" to a study, but it should only be visible to the PI/RM/Admin. It seems like we should therefore incorporate it into #109 .

**Comment by stevenday** [comment]
This has now changed, and we'd like to manage collaborators as a separate model which admins can manage, and then connect these to Studies from the admin (not from the public side of the site)..

**Comment by stevenday** [comment]
This is now done and on the staging site for testing. There's a new option "Collaborators" in the admin that lets you add organisations just like you can edit other options on the site:

![screen shot 2016-03-22 at 15 43 41](https://cloud.githubusercontent.com/assets/663700/13957617/f2b86460-f044-11e5-8b4d-41cdfc22c23d.png)

Collaborators have a name and a description, it's mainly the name that's shown, but the description is there in case you need to add some more info for your own use.

![screen shot 2016-03-22 at 16 05 45](https://cloud.githubusercontent.com/assets/663700/13958433/f60f56b6-f047-11e5-9414-ab6751251206.png)

These options then show up on the study admin page where you can assign one or more collaborator to a study:
![screen shot 2016-03-22 at 15 45 37](https://cloud.githubusercontent.com/assets/663700/13957678/2c1b5afa-f045-11e5-9777-2432c0d2e10a.png)

You can filter studies by this field in the admin to quickly see who's connected to which collaborator, and it's also exported in the CSV file.

**Comment by kimmwest** [comment]
Hi @stevenday , thanks for this.  This is shaping up really well.  One point we discussed with Ben was the fact that we have collaborations at both an institutional and individual level.  i.e. we would want to track the collaboration with both the individual research and the organisation they belong to.  IS there a way we can filter by individual and institution in the system?  Thanks, Kim x

**Comment by BenJam** [comment]
*leans in* ISTR the question bing asked about individuals or institutions and saying ys you could add either of these. I think on 14th March I sent 

>Collaborator management features:
1) That collaborators (organisations or individuals) can be added to the system
2) For each study an admin can add a number of these collaborators to a study
3) that administrators can filter studies by collaborators. 

I can see the point about individuals within institutions, but it might make a bit of a mess if we're trying to map the often complex relationships between people, projects and organisations. Esp if an individual is working for >1 organisation across the system. 

Instead of trying to model something that's quite flexible in real life we could use collaborators to indicate organisations and the research team to show individuals within those organisations. i.e. collaborator: TMIH, research team member: 'Steve @ TMIH'. Or do something similar with collaborators 'TMIH | Steve Day'?
