### ISSUE TITLE
Review new design of study timeline, documents sidebar and publications sidebar

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#107]
We've now updated the design of the study page (Feature: #3), to include all of the elements in the timeline in a better format, have links to the documents and show details of publications/impacts:

![screen shot 2016-02-11 at 14 12 38](https://cloud.githubusercontent.com/assets/663700/12978576/abf5ede4-d0c9-11e5-85b3-fea4a602164d.png)

If you could take a look at those changes and let us know what you think, that would be great.

Still outstanding at the moment are:
- adding collaborators (#100)
- stopping people who aren't logged in from adding contributions (#101)
- stopping people who aren't logged in from downloading documents (#66)
- "following" studies: #20
- updating the ERB status #18 
- nominating other people to add impact #67

**Comment by kimmwest** [comment]
This looks great - I'm really happy with how it is looking.  As mentioned in another ticket it would be good to know how things that 'need attention' are displayed on the timeline but I guess we will have to wait until the staging site is updated

**Comment by stevenday** [comment]
Thanks @kimmwest  - yes, we've addressed the "needs attention" bit in the current sprint, I'll update the relevant ticket about that in a moment.
