### ISSUE TITLE
Review basic user dashboard

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#108]
We've created a user dashboard (part of #2) which looks exactly like the homepage, but only includes studies where the current user is either the PI or RM:

![screen shot 2016-02-11 at 14 20 58](https://cloud.githubusercontent.com/assets/663700/12978736/b9ca4662-d0ca-11e5-91c5-adbb9fdd9538.png)

Users should only be able to access their own homepage, except for admins, who can access anyone's.

It'd be great if you could check that this is working satisfactorily from the point of view of listing the correct studies etc, before we move onto the search/filtering features.

**Comment by kimmwest** [comment]
Hi @stevenday - This looks great.  From the point of view of the research manager they would like to be able to quickly filter and see studies that 'need attention' i.e. are overdue or who have reported delays in our reporting cycles.  I know this functionality isn't incorporated in the staging site yet so perhaps might become clearer at the next sprint meeting

Cheers,

Kim

**Comment by stevenday** [comment]
Yep, the quick filters for studies that are overdue is one of the things we've done this sprint. I'll close this one for now, there'll be a new ticket to comment on for the final sprint's work.
