### ISSUE TITLE
Break out "Add impact" form onto its own page

### ISSUE THREAD

**Issue by zarino** [mysociety/remit#109]
The form has become too complex to be comfortably housed on the study page.

Breaking it out into its own page will make it easier for us to:

* Invite contributions from external collaborators, without showing the full study timeline and associated documents/uploads (#67)
* Let us assign impacts to multiple studies at the same time (#21)

**Comment by zarino** [comment]
I'm thinking something like this:

![impact](https://cloud.githubusercontent.com/assets/739624/13052673/13c991ba-d3f8-11e5-81be-369baf41ebc5.png)

I'm not sure whether there should be navigation at the top for logged-in users. My gut instinct is that there shouldn't be – the user is partway through a transaction, and any links away from that path might cause them to lose data.

Since the page is accessible by anonymous users too (invited by email, as per #67) it reuses the light blue background from the login/password pages. Sort of a subtle hint that it's not a "normal" page.

**Comment by stevenday** [comment]
> In hindsight - Not sure that 'output' is clear suggest we refer to it as 'dissemination or impact'

> Also, could we change the categories to
> Publication 
> Other dissemination
> Impact
