### ISSUE TITLE
Make confirmation of successful submissions more obvious on the 'add impacts' form

### ISSUE THREAD

**Issue by BenJam** [mysociety/remit#137]
![screen shot 2016-02-24 at 14 35 48](https://cloud.githubusercontent.com/assets/158833/13288538/455de8ee-db04-11e5-9d30-01feb884f179.png)

**Comment by BenJam** [comment]
I would lose the pale blue background.

**Comment by stevenday** [comment]
I think my solution to this might be to include more information in it, so that it's bigger (though I agree perhaps it should be successful green too). It might help (especially when using the DOI field) to see a confirmation of what you just added.

**Comment by stevenday** [comment]
Another useful idea here would be to show either all of the stuff you've added to the study, or in fact all the stuff *everyone's* added, to help you remember if you make multiple visits/have a lot of things, and to help avoid dupes.

**Comment by stevenday** [comment]
This has been brought up by the user testing too, I'm merging #165 into this.

**Comment by stevenday** [comment]
@zarino  - I'm going to do a basic pass on this based on https://github.com/mysociety/remit/issues/137#issuecomment-190133861, then you'll have something to play around with.

**Comment by stevenday** [comment]
I've added some lists of things that you've added (which work from an invite-token or for logged in users) in issues/137-confirming-successful-submissions (51f6ce91505745421eeb8acf95ff22d98fcc75ab). @zarino - this is probably ready for you to take a look at now, so I'll assign to you.

**Comment by kimmwest** [comment]
Hi there, this looks much better and is a lot more obvious!  Thanks!  Happy for you to close this ticket
