### ISSUE TITLE
Fix 'Add' buttons on smaller devices

### ISSUE THREAD

**Issue by BenJam** [mysociety/remit#143]
On smaller devices the 'add' buttons are quite crowded. Feel like they should b full width at some point and separated a little more. 

http://remit.staging.mysociety.org/studies/98

![screen shot 2016-02-26 at 08 52 01](https://cloud.githubusercontent.com/assets/158833/13347564/8fff36d8-dc66-11e5-9da4-031dd19ec947.png)

**Comment by zarino** [comment]
There are now only 2 buttons: "Document" and "Note", so the button list doesn't wrap any more.
