### ISSUE TITLE
Delivery indicators

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#145]
For studies in the "Delivery" phase, not much information is captured at the moment. MSF would like to send a periodic email to all PIs and capture some detail from them about how they're going. This will then be displayed on study dashboards in the form of an additional info box:

![di485kfdrb](https://cloud.githubusercontent.com/assets/663700/13640922/7ce74016-e60e-11e5-954c-c6f658a0c58b.png)

The general idea is that study delivery has three separate sub-sections: data collection, data analysis and Interpretation/Write up. Each of these sections can be in a selection of states:
- Not started
- Progressing fine
- Minor problems or delays
- Major problems or delays
- Completed

Along with this info, there should be a way to add general updates/comments as free text.

Admins need a way to trigger the sending of the emails from the admin dashboard.

**Comment by stevenday** [comment]
This will replace the enabler/barriers and the feedback and suggestions field on studies.

**Comment by stevenday** [comment]
Sketching this out, I think the code for this will look like:
- [ ] A new model: `StudyDeliveryUpdate` with three enum fields: `data_collection`, `data_analysis` and `interpretation_and_write_up`, each of which has the options: `Not started`, `Progressing fine`, `Minor problems or delays`, `Major problems or delays` and `Completed`. Then an additional comments text field.
- [ ] A new model for invites to create a `StudyDeliveryUpdate`, these need to record the study, invited user, and the access token. These should probably expire the next time an admin sends out invites. It would be helpful to record if/when an update is actually added from this invite, so that we can see which have been completed and which haven't.
- [ ] A new page for creating these updates, which requires a logged in user or a token to access. A nice feature of this would be to suggest other studies they need to update after they submit the form.
- [ ] A new mailer for sending invite emails to the users. Since most users will have more than one study, it probably makes sense to send one email with multiple links to give the feedback in, rather than one for each invite.
- [ ] A new button on the admin homepage to trigger the process of sending - presumably this should send the emails asynchronously, because otherwise it's going to be sending *lots* of emails.
- [ ] A new partial view to display the details in a `StudyDeliveryUpdate` in the dashboards

**Comment by BenJam** [comment]
Not in addition to this that any project with a delayed indicator should be marked for the attention of the RM/Admin and that the study will be marked as delayed until the next update coms in from the PI.

**Comment by BenJam** [comment]
note also that w are going to remove the 'enabler/barrier' reporting on the project page in lieu of this nw delivery reporting. Delays in patient recruitment/delivery from that feature are effectively replicated. Barriers to dissemination will be removed and dealt with directly if a completed project has no impact after 12 months.

**Comment by stevenday** [comment]
This is now done an on the staging site for testing.

The process begins with a new item on the admin homepage:

![screen shot 2016-03-22 at 16 07 10](https://cloud.githubusercontent.com/assets/663700/13958488/2a050b96-f048-11e5-8f96-e262afeb929d.png)

This takes you to a confirmation page that shows you who'll receive emails and gives you a button to send them:

![screen shot 2016-03-22 at 16 07 43](https://cloud.githubusercontent.com/assets/663700/13958515/46dce838-f048-11e5-92e7-3507a3862068.png)

There are also admin pages for individual updates that people have left (or to create one manually), the "invites" that allow people to create them in the first place, and the options for the statuses people can select in their update:

![screen shot 2016-03-22 at 16 11 23](https://cloud.githubusercontent.com/assets/663700/13958652/cf0fbab4-f048-11e5-8476-d1559973393a.png)

![screen shot 2016-03-22 at 16 11 28](https://cloud.githubusercontent.com/assets/663700/13958656/d33ff77a-f048-11e5-94a9-3bb5cfca51da.png)

![screen shot 2016-03-22 at 16 11 19](https://cloud.githubusercontent.com/assets/663700/13958660/d840a378-f048-11e5-849f-a6bc93fae2ca.png)

As well as getting an email when the admin hits the big button, when there's an outstanding invite for an update on a study, the invited user will see a new link on the study page too:

![screen shot 2016-03-22 at 16 13 02](https://cloud.githubusercontent.com/assets/663700/13958703/0312b33e-f049-11e5-975e-2d060dbcd551.png)

Following this, or the link in the email takes you to a new form:

![screen shot 2016-03-22 at 16 13 56](https://cloud.githubusercontent.com/assets/663700/13958822/7a29307e-f049-11e5-9bad-c6e957a40597.png)

And the process tries to guide you through completing all of the updates you need to:

![screen shot 2016-03-22 at 16 14 35](https://cloud.githubusercontent.com/assets/663700/13958841/8d6a4312-f049-11e5-82c0-55addb03b176.png)

Finally, the results of the updates are shown on the study dashboards (I selected minor delays for one element of my update for this study, so it's now flagged):

![screen shot 2016-03-22 at 16 16 33](https://cloud.githubusercontent.com/assets/663700/13958865/9d1fda88-f049-11e5-932f-1b565660d9e8.png)
