### ISSUE TITLE
CSV download of studies

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#15]
Initially, we need to know what data and fields we should be putting into the CSV.

**Comment by kimmwest** [comment]
Hi Steve,  will let you know this on Monday if OK.  CHeers,  Kim

**Comment by stevenday** [comment]
This is still an outsanding question, but the basic gist is that we'll have a CSV which exports the id and title of the study, alongside a variety of other boolean, numeric or date fields that allow some analysis of the studies (e.g. does it have recorded impact, is it delayed in completing, is it delayed in erb, etc).

Assigning to @BenJam to come up with an example CSV for us.

**Comment by BenJam** [comment]
Added initial take at https://docs.google.com/spreadsheets/d/13jj6UN15o8T9jWrFH6T5Y6Ke7R2wAv7qKboyI7fLGJI/edit#gid=0

**Comment by BenJam** [comment]
Added #116 to cover those instances where w may wish to pick up delays in MSF's own ERB process.

**Comment by stevenday** [comment]
As mentioned in #1 and #2 - it's now possible to download CSV files from the study dashboards and search pages. They should match the example CSV @BenJam created above.
