### ISSUE TITLE
Allow filtering by multiple items (e.g. HIV & TB)

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#154]

**Comment by stevenday** [comment]
@kimmwest, I've just put this up on the staging site for you to test. Each of the filters on the homepage/your studies page now lets you select multiple options, it looks a bit like this:

![screen shot 2016-07-25 at 17 29 38](https://cloud.githubusercontent.com/assets/663700/17108889/69ab4204-528d-11e6-8c0a-0f94153bee55.png)

**Comment by kimmwest** [comment]
@stevenday Hi Steve - this looks great.

We deal with co-infections a lot e.g. HIV & TB and so it is quite likely that people would want to search for studies that on 'HIV & TB' as opposed to all studes on either HIV or TB.  Is there anyway we could add some boolean search terms in or is that not posssible??

**Comment by stevenday** [comment]
@kimmwest - sorry, no, I'm afraid that's not really possible at the moment, it would require quite a big change to the way we do the searching.

**Comment by kimmwest** [comment]
@stevenday - no probs!
