### ISSUE TITLE
Add an about page to explain the system

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#158]

**Comment by BenJam** [comment]
@kimmwest we can guide you here but we'll need you to provide the content.

**Comment by kimmwest** [comment]
@stevenday - thanks Steve, this looks good.  Only quesiton I have is about the email address at the bottom - will we need to create that or does it come within ReMIT?  Cheers, Kim

**Comment by stevenday** [comment]
@kimmwest - yes, we will need you to give us an email address for that, though you don't need to create one if there an existing one that people use already? (It's very easy to change what's shown on the page).
