### ISSUE TITLE
Add tooltips to the various stage labels/badges

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#159]
To explain exactly what each one means.

**Comment by stevenday** [comment]
Assigning this to @kimmwest in order to show we're waiting on MSF supplying the labels for these (along with other explanations for the impact form).

**Comment by kimmwest** [comment]
Hi @stevenday  - I sent the labels across for this but can't see that they've been added.  I am assuming that the tooltips refer to the lables for 'concept' 'delivery' etc....but correct me if I am wrong.  Cheers, K

**Comment by stevenday** [comment]
@kimmwest - I've added them to the little badges that are shown in lists of studies. They look like this:

![screen shot 2016-07-27 at 13 17 41](https://cloud.githubusercontent.com/assets/663700/17174899/92425926-53fc-11e6-8baf-39ff558c6c47.png)

Do you not see this (there might be bug) or is this not where you were expecting them to be?

**Comment by kimmwest** [comment]
@stevenday Ahhhhh Ok sorry, my misunderstanding.  In my head they would also be on the individual study page as well i.e,  so if you hover over the various stages running over the top of the page, the description would appear.  Can they can be added here too or is that not possible?

Cheers

K
