### ISSUE TITLE
"Quick Filters" for finding lists of studies that match certain criteria

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#16]
We need to discuss what these criteria are

![all-studies-logged-in](https://cloud.githubusercontent.com/assets/739624/11899374/51f4823c-a596-11e5-9fdd-9ef510a3d091.png)

**Comment by kimmwest** [comment]
Do they have to be the same for each level of user or not?  

Will let you know on Monday

**Comment by BenJam** [comment]
stepping in on the grounds of time management, it would be best (and it was our initial intention) that these filters would be useful to RM/admins/PIs involved in the process of managing a study. Might not be useful for those merely 'viewing the site casually'

**Comment by stevenday** [comment]
These are now specifically for RMs and admins users (PIs don't have enough stuff to filter to need them) and there's only one - studies that are delayed.

**Comment by stevenday** [comment]
These are now implemented - I made one filter for each of the types of study that we alert about in #4 (which are also the same things that cause studies to be flagged as "needing attention" in #17) See #17 for details of how to change the values on the studies so that they come up in these filtered lists.
