### ISSUE TITLE
Spell out what ReMIT means

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#160]
i.e. Research and Management Information Tool

**Comment by kimmwest** [comment]
Hi @stevenday , thanks for this - it's actually  Research Management and Impact Tool.

Cheers, K

**Comment by stevenday** [comment]
@kimmwest - I've changed this now - is this what you were expecting, or would you prefer it was a tooltip when people hover the logo/name instead?

**Comment by kimmwest** [comment]
@stevenday - perfect!
