### ISSUE TITLE
Differentiate the studies which have "minor delays" from those with "major delays"

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#161]
e.g. the first item in this screenshot should have an orange title, not red:

![screen shot 2016-06-20 at 12 40 19](https://cloud.githubusercontent.com/assets/663700/16193016/9ce3e302-36e4-11e6-8a19-ff9a693a69fc.png)

I think we took a shortcut to get this styling because we re-used the existing mechanism for saying "this study has a problem" relating to ERB delays etc. We'll have to revisit this to make it less binary.

**Comment by stevenday** [comment]
After discussing this, the main change is going to be to colour the badge (which is currently red or green) in orange too, if there are minor delays.

**Comment by kimmwest** [comment]
Hi @stevenday - can you clarify how an ERB delay is differentiated from a 'research management' delay?  This isn't so clear to me.  Sorry if I'm missing something obvious

**Comment by stevenday** [comment]
@kimmwest - I thought after we discussed this we decided that the issue was not so much that they needed differentiating, but that having the whole title go red along with the stage badge was overwhelming. Now just the stage badge changes colour (and it can be one of three colours, not just red/green).
