### ISSUE TITLE
Differentiate between studies which are delayed because of ERB vs those delayed from something in the interim progress report

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#163]
> It is difficult to see which have turned red due to ‘ERB delays’ vs ‘research management delays’ – How can we make this more intuitive?

**Comment by zarino** [comment]
Answers from the MSF team:

* Only add the `.list-of-things__list__item--attention` class to a study in the list if it is one of *your* studies. People unrelated to the study don't need to pay attention to delays in that study.
* `.list-of-things__list__item--attention` shouldn't make the study title red. Just the study stage badge.

@stevenday – how does this ticket relate to https://github.com/mysociety/remit/issues/161 ?

**Comment by stevenday** [comment]
@zarino - #161 is a ticket to make the study stage badge orange if there are minor delays (as opposed to major delays).

**Comment by stevenday** [comment]
I've removed the design label since we have a clear idea of what we're going to do here and it's all in the code now.
