### ISSUE TITLE
Make it clearer that if you fill out multiple sections of the impact/dissemination form, only the selected one will be submitted

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#167]
Users interpreted this page as allowing you to submit multiple pieces of data in one go, rather than choosing a form to submit from several options. 

I guess we can explain that better in text, and add some kind of alert/dialog if you fill out data and then switch forms.

**Comment by zarino** [comment]
See also https://github.com/mysociety/remit/issues/137 – making the feedback more obvious after you've submitted the form.

**Comment by stevenday** [comment]
I've done the dev work for this as part of #137 since I was in the form anyway.  See: ce7837a87a021e356b94b4d559daddd3ae7d19dc in the issues/137-confirming-successful-submissions branch

**Comment by stevenday** [comment]
I'm not sure this *needs* any design work, but I'll leave that to the designer to decide :)

**Comment by kimmwest** [comment]
As with 137 - this looks great!  Thanks @Zarino  @stevenday
