### ISSUE TITLE
Mark studies as needing a PI or Research Manager's attention

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#17]
We need to know what makes a study need someone's attention - just a deadline passing, or an ERB status change too?

**Comment by stevenday** [comment]
I think the current consensus on this is that an admin will be able to manually mark a study as needing attention, as well as it being triggered by a deadline passing. However, we need to think about what receiving attention actually means, is it as soon as the PI loads the page, or do they need to do something to clear it?

**Comment by kimmwest** [comment]
hmmmm this is a good point, I hadn't thought about whether it required an action to clear it.  Another thing that I will discuss with Sarah on Monday if this is OK?

**Comment by stevenday** [comment]
After some discussion, "needing attention" is not quite the right word for this, it's more "studies with something you need to be aware of" - We can't use the terminology "flagged" because that means something else within MSF, but it's essentially that.

Because of this, my question about "what does the user need to do to clear the flag" isn't relevant - there's nothing they need or can do (at least within remit anyway), they just need the site to keep flagging the study to them until something about the study changes to make the flag go away.

The times when this flag should appear are the same as when it would be alerted about, e.g. it's late completing, late getting an ERB response, or its ERB approval is about to expire.

Therefore, this should probably wait until we've done #69

**Comment by stevenday** [comment]
Oops, re-opening this so that it's ready for review

**Comment by stevenday** [comment]
As mentioned in #2, this is now completed. Studies which need attention are flagged on the user's study dashboard and on the page for the study itself by being highlighted in red.

@kimmwest - to test this, you'll need to assign some studies to yourself (either as PI or RM) and then force some of them into a state where they "need attention". For example, you can set the expected completion date to a date in the past; set the study stage to delivery and the erb_approval_expiry to a date in the past or within 3 months of now; or you can set the study stage to protocol, the erb status to submitted and the erb_submitted date to a date at least 3 months in the past.
