### ISSUE TITLE
Automatically generate OCA reference numbers

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#171]

**Comment by stevenday** [comment]
The plan here is to add something that prefills the admin form with an auto-incrementing number, allowing admins to override or edit it if needs be, but without needing to figure out what it should be for truly new studies.

**Comment by stevenday** [comment]
@kimmwest - this is now up on the staging site to test. On the form for adding a new study the reference number is automatically filled in, incrementing from the last number that's in the database (so you don't need to tell us a starting number at all). However, you can just change this manually if you want to add an existing study that already has a number.

For example, looking at http://remit.staging.mysociety.org/admin/studies/new right now, I get the reference number of OCA016-6. It looks like some of the recent ones you've added have a number like 004 or 05 (rather than just 4 or 5) - would you prefer that I prefixed the auto-generated ones with zeros too, or is it ok as-is?

**Comment by kimmwest** [comment]
Hey @stevenday - I've spent the past couple of days in AMsterdam uploading the data to the system and I learned that our concept note numeration is a bit of a mess!  ReMIT will fix that, which is great :) We do not want double zeros e.g. OCA016-006 but we would like one zero to the suffix e.g. OCA016-06 and then onto OCA016-10 and so on.  DOes that make sense??

**Comment by stevenday** [comment]
@kimmwest - yep, that makes sense. I'll look at changing that.

**Comment by stevenday** [comment]
@kimmwest - This is now done - it prefixes reference numbers 1-9 with a zero.
