### ISSUE TITLE
Email text updates

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#175]
We need to provide MSF with all of the email templates and let them update the copy.

**Comment by stevenday** [comment]
@kimmwest - here are some links to the templates we use for sending emails from the site.

As you'll see, there are quite a few different emails that go out, but hopefully from the text of them it's easy to work out what they're for.

They are all templates, so you'll see things in them like `<%= @study.title %>`. When you're editing them you can change any of the other text, but the bits between `<%=` and `%>` have to stay, as they're how the data is output into the final email. If there's other data you'd like to include in any of them, or you want to change what data is included, ask and we'll take a look.

Templates for alert emails (e.g. your erb approval is expiring, your study is delayed, etc):
https://github.com/mysociety/remit/tree/master/app/views/alert_mailer

Template for invites to add annual updates:
https://github.com/mysociety/remit/tree/master/app/views/annual_update_mailer

Templates for user approval emails (e.g. email to admin about new user, email to user saying they've been approved):
https://github.com/mysociety/remit/tree/master/app/views/approval_mailer

Template for invites to add interim delivery updates:
https://github.com/mysociety/remit/tree/master/app/views/delivery_update_invite_mailer

Template for invites to contribute to a study:
https://github.com/mysociety/remit/tree/master/app/views/study_invite_mailer

I've assigned this to you for now to show we're waiting on the new text before we do anything further.

**Comment by stevenday** [comment]
@kimmwest - In the email text you supplied, there are two deadline dates. How are these calculated? At the moment I've gone with two weeks from when the emails are sent, but I can change that to any period you like..

**Comment by kimmwest** [comment]
Hey @stevenday  - it's the deadline for our annual reporting cycle so if I'm unable to change it  could probably do with being 4 weeks from when the email is sent instead.

**Comment by stevenday** [comment]
@kimmwest ah, yes, setting a date like that is more tricky. If it's the same date every year we could work it out, but I'm guessing it's not? In which case, 4 weeks from sending would be easiest

**Comment by kimmwest** [comment]
@stevenday No it's not but every 4 weeks is fine - i'l just have to remember.  It would be good if the study title could feature next to the OCA reference.  I've tried to test the delivery reporting emails but they don't appear to be coming through?
