### ISSUE TITLE
Studies should be archived after 5 years, not 3

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#177]

**Comment by stevenday** [comment]
@kimmwest - I've just been looking at this, but the code is currently slightly more nuanced than just "3 years". It currently archives studies that have been *completed* more than *1 year*ago. 

Should I be changing that 1 year to 5, or basing it off a different date (e.g. when the study starts delivery, or is first added), or both?

**Comment by stevenday** [comment]
For my own reference, the code for this is here: https://github.com/mysociety/remit/blob/ded3b69ea57e6c103af7ce30e016f3f88b11e47e/app/models/study.rb#L197-L200

**Comment by kimmwest** [comment]
It should archive studies that have been completed more than 5 years ago. Thanks, Steve
