### ISSUE TITLE
Add a field to ask whether a study has been withdrawn or postponed during interim updates

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#178]

**Comment by kimmwest** [comment]
As discussed in our meeting, this does not need to be a field at the moment, instead we can add some text to the bottom of the delivery reporting emails and tell people to email me if a study has been postponed

**Comment by stevenday** [comment]
I'd actually already done this, just forgot to close this ticket. It looks like this:

![screen shot 2016-07-25 at 11 37 12](https://cloud.githubusercontent.com/assets/663700/17099006/848d151e-525d-11e6-8e0a-b15f14caba81.png)

**Comment by kimmwest** [comment]
Hey @stevenday This looks great - I think you said that the ReMIT inbox won't go live until the site is off the staging site?  Is that correct?
