### ISSUE TITLE
Recording the current ERB status against studies

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#18]
e.g. Awaiting the ERB's decision, ERB requires revisions, etc.

We need to discuss if this is necessary or not, as it's in the initial data model, but in our discussions it sounded like it might be superfluous.

Related to #17 because these sub-statuses might be a good thing to alert people about.

**Comment by stevenday** [comment]
@kimmwest - What's the current status of this feature, is it something you still think you need, or can we leave it? I ask because if we need it, it would be useful for us to tackle this soon..

**Comment by kimmwest** [comment]
Hi Steve, are you working off the data schema I sent you or our interim database?  In the schema the status' we would need are exempt (i.e. can move straight from concept paper stage to delivery), submitted, reject, requires revisions, re-submitted, approved

It is useful for each interaction to the ERB to be documented and date stamped so we can drill down and find out why there are any delays

Is this what you meant?  Cheers,  Kim

**Comment by stevenday** [comment]
@kimmwest - my apologies, that's exactly what I was talking about and I see now how it all fits in. We do indeed have the fields from the schema to store those statuses and track the changes in the timeline.

One remaining question that comes from this is who is allowed to change the ERB status, is is just admins, or do PIs/RMs need the function to do it too?

**Comment by kimmwest** [comment]
hi @stevenday  - I'd say give this functionality to everyone, although in reality it will just be the admins.  PIs/RMs also need to be able to move their studies along the different stages - e.g. from delivery to completion etc

**Comment by stevenday** [comment]
After discussing this in the sprint review, we're exchanging this for #110, where PIs/RMs can move a study from protocol to delivery and then from delivery to completion from the study page.
