### ISSUE TITLE
Add explanations under the options on the impact/dissemination form.

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#181]
Assigning this to @kimwest to show we're waiting for the text for these.

**Comment by stevenday** [comment]
Related to #159

**Comment by stevenday** [comment]
@kimmwest - I've put these descriptions in, they are quite long, although I don't think it causes too many problems personally. Here a couple of screenshots if you want to check yourself (you can see this on the staging site now too).

![screen shot 2016-07-22 at 12 23 17](https://cloud.githubusercontent.com/assets/663700/17055824/4881e368-5007-11e6-9598-c6879d50008f.png)


![screen shot 2016-07-22 at 12 23 26](https://cloud.githubusercontent.com/assets/663700/17055818/40ff5904-5007-11e6-8362-7cf501fa691e.png)

**Comment by kimmwest** [comment]
@stevenday Hey Steve, this looks great. Not too bothered about it looking crowded - it's best to be clear.
