### ISSUE TITLE
Leaving notes on studies

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#19]
Can anyone leave a note, or only people assigned to the study?

**Comment by stevenday** [comment]
Apart from the issue of who's allowed to leave a note, which we'll tackle later, this is now completed.

To leave a note you need to visit a study's page, and then click the "Add a note" button above the timeline:

![screen shot 2016-01-27 at 16 45 09](https://cloud.githubusercontent.com/assets/663700/12620746/67a328b0-c515-11e5-822e-adc40491eeae.png)

You can then submit the form which will save it (your note will appear in the timeline so you know that it's worked).

You can also view all of the notes people have left in the admin:

![screen shot 2016-01-27 at 16 46 37](https://cloud.githubusercontent.com/assets/663700/12620787/8faabb34-c515-11e5-9ddc-c7d8fa8d8c9a.png)

Which allows you to edit them/delete them, or add a new note as with other bits of data.

**Comment by kimmwest** [comment]
I think that we should restrict those that can leave a note on a study to administrators, research managers, PIs and anyone who assigned to a study.  Not everyone who uses the system should be able to leave notes on random studies. 

In the admin part can you see who has left a note or not?  Cheers, KIm

**Comment by stevenday** [comment]
Thanks @kimmwest - I've created #101 to handle controlling who can leave notes and #102 to deal with putting names against them so you can see in the admin who left it.

I'm going to move this back to the backlog until those are done and this is ready for review again.

**Comment by stevenday** [comment]
Both #101 and #102 are now done, so this is ready for a re-review @kimmwest

**Comment by kimmwest** [comment]
Hi @stevenday this looks great.  No comments from my side.
