### ISSUE TITLE
Hide "hidden" studies from everyone except their PIs/RMs and Admins

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#198]
At the moment (as per #65) they're shown to anyone who's logged in.

However, @kimmwest requested that they be more private.

> When studies are hidden, they need to be hidden to everyone, apart from system admins and the PI/research manager.  I think at the moment they are showing to anyone who is logged in.

**Comment by stevenday** [comment]
@kimmwest - I've done this work now and put it up on the site for you. Do you want to check it's working how you expect?

**Comment by kimmwest** [comment]
@stevenday Hi Steve, it's not working as expected.  When I logged in as myself (with my personal email - listed as a non-admin) I could see all of the studies.  They PIs will still need to report on their study outcomes but it shouldn't be visible to anyone else bar admins

**Comment by stevenday** [comment]
@kimmwest - Hmm, looking in the site admin, I can't see any studies which are marked as hidden? Which studies are you seeing that you expect to be hidden, and how have you hidden them?

**Comment by kimmwest** [comment]
@stevenday Hi Steve, sorry, I deleted them as my colleague didn't want them visible on the site unless they were hidden.  I've re-added one and had the same problem.  It's titled 'Effectiveness of TB treatment regimens containing bedaquiline for Extensively Drug Resistant Tuberculosis patients in Chechnya'.  I marked it as hidden by checking the 'hidden' box.  Do I need to do anything else?

**Comment by stevenday** [comment]
@kimmwest my apologies, no, you don't need to do anything else, I'd made a mistake with the code because of temporary changes we've made to the email sending and so these changes weren't actually on the live site yet. They are now, and the studies are being hidden correctly for me. Apologies again.

**Comment by kimmwest** [comment]
@stevenday thanks a million, Steve.  Just to check - do the emails sent for the delivery updates and impact updates still go to me??

**Comment by stevenday** [comment]
@kimmwest yep, they still do
