### ISSUE TITLE
UI snags

### ISSUE THREAD

**Issue by zarino** [mysociety/remit#39]
If you spot a tiny thing that looks broken but doesn't really warrant its own ticket, add it to the list!

* [x] "Update" button on the Devise "Edit User" page needs a bootstrap `btn btn-primary` classes
* [x] The red "flag" badges on study pages and list pages (https://github.com/mysociety/remit/pull/120) need attention
* [x] `<select>` elements on list pages need bootstrap `form-control` class
* [x] More vertical space between `.study-main__primary` and `.study-main__secondary` on narrow screens (fixed by 534b92b3c6ac3062a583e53ea1735d499c7bf563)
* [x] The ellipsis on the pager for studies is always at the end, when it's supposed to be in the middle of the numbers. (Looks like the elipsis needs to be wrapped in a `span`.)
* [x] The stage progress bar background colour doesn't work when a study is just in the concept stage (fixed by https://github.com/mysociety/remit/pull/71)
       ![screen shot 2016-01-22 at 13 28 25](https://cloud.githubusercontent.com/assets/663700/12511806/2fdf6400-c10c-11e5-899f-a16843b4bb80.png)
      
      Or when the study has completed more than one stage:
      ![screen shot 2016-01-22 at 13 30 29](https://cloud.githubusercontent.com/assets/663700/12511867/7850933a-c10c-11e5-8de1-e5003002947b.png)

**Comment by stevenday** [comment]
Closed in 8e1f5bb57939ec341c20949b2b8e989e1be32687
