### ISSUE TITLE
Review homepage and study page for basic details and listing of studies

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#40]
We've done some very initial work on the homepage, so that it lists studies in the database and allows you to page through them, with links to each study:

![screen shot 2016-01-14 at 15 52 50](https://cloud.githubusercontent.com/assets/663700/12329173/e6f06d7e-bad6-11e5-8191-74f790a0483c.png)

We also built the basic page for each study, so that it can be linked to and shows the title, type, stage and topic of the study:

![screen shot 2016-01-14 at 15 53 20](https://cloud.githubusercontent.com/assets/663700/12329184/f630ecdc-bad6-11e5-9719-7eea63073925.png)

The aspects of functionality these cover are parts of #1 and #3, but because they're such minor parts, I've made a separate ticket just to get any feedback on these initial pages, without cluttering up those main tickets. Whilst most of the functionality *doesn't* work, and these pages are only showing basic data about the studies, they should *look* right, even when viewed on mobile phones or tablets, so it would be great if you could look at it superficially at least to confirm that. Otherwise, we don't expect much feedback at this stage, until we start to flesh out the features a little more.

**Comment by kimmwest** [comment]
This looks great.  Super happy. No major comments.  Will leave feedback to specific components on individual tickets

**Comment by stevenday** [comment]
Thanks @kimmwest - I'll close this then. We'll have future tickets for you to review when we look at the search pages and other aspects of the homepage.
