### ISSUE TITLE
The country field should be a nice select box of ISO3166 countries

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#41]
The database field is ready to store the two-digit code, and we have the right ruby gem available to turn this into a country with a nice name, but we need to link the two up.

For #23 and #8

**Comment by zarino** [comment]
Does it need to allow multiple countries to be selected at once? (ISTR Kim mentioning that some studies might have more than one location)

**Comment by stevenday** [comment]
It was listed as a single select box in their schema, but it's worth checking
