### ISSUE TITLE
Review adding documents and outputs to studies

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#58]
We've now added the forms for people to contribute documents and the various kinds of output to the Study page (See #3 for the original wireframes and full list of things that page should do).

To add a document, click the "Add a document" button and then select the file from your computer as well as the type it is.

![screen shot 2016-01-27 at 16 57 54](https://cloud.githubusercontent.com/assets/663700/12621142/23333c68-c517-11e5-8b46-d14f715aaf15.png)

It should be shown in the timeline so you know it worked (though it won't link to anywhere yet), or you can check the admin page for documents:

![screen shot 2016-01-27 at 16 59 02](https://cloud.githubusercontent.com/assets/663700/12621185/50275b50-c517-11e5-9786-a076ca8fab56.png)

Outputs work in a similar way, but because there are more options there's an extra step of picking which kind of output you're adding:

![screen shot 2016-01-27 at 17 04 46](https://cloud.githubusercontent.com/assets/663700/12621582/1d882b96-c519-11e5-847e-bc5c6347fee2.png)

Publications currently only allow you to create them manually:

![screen shot 2016-01-27 at 17 04 57](https://cloud.githubusercontent.com/assets/663700/12621604/32718502-c519-11e5-9830-acb093ae77c2.png)

Disseminations are fully functional, except for the text field that appears when you select an "other" category:

![screen shot 2016-01-27 at 17 05 05](https://cloud.githubusercontent.com/assets/663700/12621645/5f72ca3e-c519-11e5-8593-9d12c7e09161.png)

Finally, impacts allow you to create multiple impacts at once by checking as many checkboxes as you need to and then entering all of the descriptions:

![screen shot 2016-01-27 at 17 15 26](https://cloud.githubusercontent.com/assets/663700/12621684/96d3811c-c519-11e5-9bbf-32e8df1f4c0f.png)

As with documents, all of these are also manageable from the admin:

![screen shot 2016-01-27 at 17 16 11](https://cloud.githubusercontent.com/assets/663700/12621734/d4cf1896-c519-11e5-9749-ab10debecf93.png)

![screen shot 2016-01-27 at 17 16 30](https://cloud.githubusercontent.com/assets/663700/12621735/da97a9c8-c519-11e5-9d13-e77bbddb982c.png)

![screen shot 2016-01-27 at 17 17 39](https://cloud.githubusercontent.com/assets/663700/12621756/e80335b4-c519-11e5-82cf-95e8563a20e9.png)

**Comment by kimmwest** [comment]
Hi Steve,  
This looks great.  Couple of comments 
In hindsight  - Not sure that 'output' is clear suggest we refer to it as 'dissemination or impact' 

Also, could we change the categories to
Publication 
Other dissemination
Impact

We also need explainers for each of the categories but I guess that comes at a later date?

I also think that the 'Have you fed back to the field should be changed to 'Have you fed back to people in the country or region in where the study was conducted'?  And then a free text box instead of a  

Also, when you add a document can we remove the document type 'dataset' - we can't store those in the system.  

Cheers

Kim

**Comment by stevenday** [comment]
Hi @kimmwest,

Thanks for the feedback, I've created three new tickets to track your comments independently: #92 #93 #94.

I'm going to close this one since it was only a temporary ticket for our work last sprint and we should have a new one for this current sprint with the new stuff we've done on the study page.

**Comment by stevenday** [comment]
Sorry - I meant to also reply to @kimmwest's question:

> We also need explainers for each of the categories but I guess that comes at a later date?

To say that these have now been added (and they're up on the staging site), and I'll explain them at the next sprint meeting.
