### ISSUE TITLE
DOI Resolution

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#6]
This ticket describes the functionality that will be present to resolve DOI identifiers and store metadata about publications when uploading evidence of impact.

![study-adding-publication](https://cloud.githubusercontent.com/assets/739624/11899333/0670fdcc-a596-11e5-8a8b-731aa72c6c14.png)

### PIs
- [x] Can input a DOI when adding a publication to a study, and have the metadata populated automatically

**Comment by davea** [comment]
crossref.org provide an [API](https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md) ([also](http://search.crossref.org/help/api)) which returns JSON for DOI lookups, e.g. https://api.crossref.org/v1/works/http://dx.doi.org/10.1145/2785830.2785855

**Comment by BenJam** [comment]
the second part here should probably be for everyone.

**Comment by stevenday** [comment]
I've added this feature now - it's also mentioned in #3, but if there are specific comments about how it works, please add them here.

One issue I had with testing this is not having a decent selection of sample DOIs that people might input. I've tested it with some classic papers that it was easy for me to find DOIs for, but it could ideally do with a better sample being obtained from some of MSF's actual data and testing with those.

**Comment by kimmwest** [comment]
Hi Steve, this isn't working for me.  I tried with this DOI 10.1093/inthealth/ihu086 but the there isn't a button next to the field to say 'search' and when I clicked 'add output' the entire page just reset.

**Comment by stevenday** [comment]
Hi @kimmwest,

I think you've just reinforced our need to look at this ticket: https://github.com/mysociety/remit/issues/137. If the page just reloaded (without any errors, which I don't think there were because I just tested that DOI here and it works) then the publication was actually added successfully. There was a small message at the top to tell you this, but you missed it because it was too small and insignificant against the blue background of the page. 

Before we moved this form to a separate page we didn't have this issue because you could see what had just been added in the timeline and the sidebar. Now that it's on a separate impacts page you don't. I think we need to improve this as we're discussing in #137

**Comment by kimmwest** [comment]
@stevenday - ah, sorry I didn't see that,  It looks good on the timeline but agree it should be more obvious
