### ISSUE TITLE
Archival of studies that have completed more than 12 months ago

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#64]

**Comment by zarino** [comment]
Note this will probably require some changes to the study page subnav (the progress breadcrumb), to accommodate a 6th item.

**Comment by stevenday** [comment]
The idea is that all studies are either "Active" or "Archived". Studies are active until 12 months after their date of completion, then they are archived. Archived studies don't show up in searches etc by default, they have to be manually enabled.

**Comment by BenJam** [comment]
@zarino could this not be done with a change to monochrome for the progress? All archived studies are complete so this information is less important than those on live studies.

**Comment by stevenday** [comment]
I've actually almost implemented this already and have just done it as
another item in the progress bar - it was easy enough to do that and
doesn't affect to much else. I just need to write some tests before it's
done.
