### ISSUE TITLE
Hiding of some studies (because they contain sensitive info)

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#65]
The current plan with access control is that everything will be basically accessible (e.g. details and timeline, but not full documents). However, some special studies will be hidden so that only logged in users can see them.

**Comment by stevenday** [comment]
Admins control this by checking a checkbox on the study form when they add the study to the database.

**Comment by stevenday** [comment]
This is now done and on the staging site - as the comment above says, there's a new checkbox on the admin pages which allows you to mark a study as hidden. Hidden studies will only appear to logged in users on every part of the site.

**Comment by kimmwest** [comment]
Hi @stevenday - this feature is super useful but would there be any way of adding a filter so that we could see a list of which studies were hidden? Thanks, Kim

**Comment by stevenday** [comment]
@kimmwest - Sure, I've added that filter to the studies admin page now. I'm going to close this as finished for now.
