### ISSUE TITLE
Nominating people via email to add impact to a study

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#67]
* PI decides to invite contribution(s) from an external collaborator
* PI clicks link in the sidebar of study page
* PI enters email address (and message?)
* Email with login token is sent to the external collaborator

* External collaborator follows link from email, to special "Add impact" page
* Page shows PI’s name and project title
* External collaborator adds their name and organisation
* Fills in an impact
* "Add another" option after impact has been successfully added

**Comment by zarino** [comment]
See also #109 which covers breaking the form out into its own page.

**Comment by zarino** [comment]
I'm thinking something along the lines of this for the CTA on the study page:

![screen shot 2016-02-15 at 16 07 45](https://cloud.githubusercontent.com/assets/739624/13053795/527b22c4-d3fe-11e5-9850-fe467fa0891a.png)

First link would go straight to the "Add impact" page. Second link would open up some sort of modal or inline fold-out form, for them to send the invite.

**Comment by zarino** [comment]
@stevenday – I've done the frontend stuff for this in a97396b:

![screen shot 2016-02-17 at 13 06 54](https://cloud.githubusercontent.com/assets/739624/13110346/68769368-d577-11e5-85d6-c1570fb4c2d8.png)

**Comment by stevenday** [comment]
Oops, re-opening this so that it's ready for review

**Comment by stevenday** [comment]
As mentioned in #3 - this feature is now finished and up on the staging site. Users invited through this mechanism can visit a special page where they can submit as many impacts, publications or disseminations as they like.
