### ISSUE TITLE
It won't let me add a dissemination without ticking the "fed back to field" checkbox

### ISSUE THREAD

**Issue by zarino** [mysociety/remit#73]
I should be able to add a dissemination and leave the "fed back to field" checkbox unchecked, and it should work.

![screen shot 2016-01-28 at 15 18 43](https://cloud.githubusercontent.com/assets/739624/12648620/c0d1652e-c5d2-11e5-80e2-24b8a998e90c.png)

**Comment by stevenday** [comment]
Thanks for ticketing this

It looks like I should also make a ticket for checking all of the error
messages are actually helpful, because that one is rubbish!

**Comment by stevenday** [comment]
I've fixed this in the branch I'm working on: issues/3-creating-documents, I'll leave this open for reference until I merge that in.
