### ISSUE TITLE
Site-wide administration

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#8]
This ticket describes the site-wide administration features that will be available to administrator users to manage the site, add new studies, and so on.

### Administrators
- [x] Can add a new study by filling in the basic details (*details TBC*)
- [x] Can add new users to the site, optionally assigning them roles like Research Manager or PI
- [x] Can edit the "Topics" field options
- [x] Can edit the "Study type" field options
- [x] Can edit the "Location" field options
- [x] Can edit the "Impact type" field options
- [x] Can edit the "Document type" field options

**Comment by stevenday** [comment]
@davea is still reviewing the code for this in #30, so their might be some technical changes to *how* things are done, but hopefully the features all work, and therefore all of the user stories for this are finished in a basic sense.

We've done this in a very quick and dirty fashion because it'll help us talk about the data model and the various requirements that come from it more easily if we can visualise it and play with things through an interface. We've built this using a toolkit for admin pages, so lots and lots of things come for free "out of the box" as it were, but it needs some customising to be truly useful. That means things might not be as user-friendly as they could be (and we can work on improving that in future sprints), but the most important thing is that they should be *complete* and *correct* in terms of all the fields being there, required fields being required, and so on. I'd especially like feedback if anything isn't correct, but feedback on everything else is fine too.

### The admin site
The site admin is accessed by the "admin panel" link in the bottom right of any page: 

![screen shot 2016-01-14 at 14 05 01](https://cloud.githubusercontent.com/assets/663700/12326290/df2b8c86-bac7-11e5-8722-98a92010a3ee.png)

Or, if your user is marked as an admin, you will automatically be taken to it when you log in. It looks like this:

![screen shot 2016-01-14 at 14 06 12](https://cloud.githubusercontent.com/assets/663700/12326307/ff030016-bac7-11e5-9a6d-28ce3dda141a.png)

It has a kind of "dashboard" where we can put useful shortcuts (as an example I've made a list of studies that are "over 12 months old but haven't completed"), but it also has a menu to access other specific pages:

![screen shot 2016-01-14 at 14 08 18](https://cloud.githubusercontent.com/assets/663700/12326364/4b2b77e8-bac8-11e5-91a7-b5fe05da1d43.png)

This is where you can get to most of the features of the admin.

### Studies admin
The studies admin page gives you access to a list of studies in the database. You'll see I've added the data from your interim spreadsheet, but I haven't added every single thing at the moment because there are some complications. They're in a table which you can sort in various ways, and you can search/filter them using the filters on the right hand side:

![screen shot 2016-01-14 at 14 10 10](https://cloud.githubusercontent.com/assets/663700/12328334/d4f4dbb8-bad2-11e5-9dc9-fda0e9953006.png)

I'm not anticipating that this will be heavily used, but it will allow you to track down a study and edit it if you're already in the admin for another reason.

The main aspect of the admin is adding/editing studies. To do that you click the big "New Study" button in the top right:

![screen shot 2016-01-14 at 15 24 48](https://cloud.githubusercontent.com/assets/663700/12328374/0adcea68-bad3-11e5-80b8-5cd5147a88b9.png)

Which then takes you to a form for adding the study:

![screen shot 2016-01-14 at 15 26 10](https://cloud.githubusercontent.com/assets/663700/12328405/300dff48-bad3-11e5-84d3-47b1be0abb23.png)

This should have every field and option for you to edit a study through it's life in the system. Things like study impacts/publications/dissemination will be handled elsewhere, but when you need to say "The ERB reference for this study is xxx" (for example) this is where you'll edit it.

Editing studies happens through an identical form:

![screen shot 2016-01-14 at 15 28 40](https://cloud.githubusercontent.com/assets/663700/12328491/85a7885c-bad3-11e5-9416-0e2d4cbb6c37.png)

You'll notice that lots of the fields are drop down boxes with multiple options. The options for these are also editable through the menu option called "Field options", where each different field has a page listing it's options, allowing you to edit them and add new ones in exactly the same way as with studies.

Finally, it's also possible to access the edit form for any study from the main site, via the link at the very bottom of the right hand side of the study's page:

![screen shot 2016-01-14 at 15 39 46](https://cloud.githubusercontent.com/assets/663700/12328834/28f21ecc-bad5-11e5-93fb-c1d33e849fcf.png)

### Users admin
The admin has a very similar set of pages for managing users as those for managing studies:

![screen shot 2016-01-14 at 15 31 29](https://cloud.githubusercontent.com/assets/663700/12328693/6b7f4874-bad4-11e5-994f-3882dea8ad28.png)

You can add new users, or edit anything about existing ones (including their email address or password):

![screen shot 2016-01-14 at 15 35 51](https://cloud.githubusercontent.com/assets/663700/12328717/86c25392-bad4-11e5-84bd-af82c02fc136.png)

Note however, that when you create a new user, or change an existing user's email address, the site requires that email address to be confirmed, so it will send an email to the user confirmed, and they will have to click on the link before their account is activated (or their email address is changed).

Apart from the basic details of the user's account, there's one key field called "role". This defines what the user can do on the site. At the moment, the only role that makes a difference is being an "admin" because that gives you access to the admin site. If you create new users and want them to be able to access the admin site, you need to give them this role. 

As with other tickets, please comment on this with any issues you find with the admin site, or in creating studies/users/etc. This is a slightly more complicated ticket because it might be that we have to change the database to fix the problem, rather than the admin site as such, but putting everything here should hopefully make it easier for you to collect all your thoughts and feedback. One aspect to bear in mind though is that this isn't meant to replace any functionality we've wireframed into the main site already. So, for example, there'll still be a way for PIs/RMs to update the status of studies from the main study page, they won't have to use this admin. This is solely for admins who need access to change anything and everything about a study.

**Comment by stevenday** [comment]
One issue I've just noticed is that the country field is not a nice dropdown box as we promised. I have a plan to make that happen which I've ticketed (mainly for my sake) at #41

**Comment by stevenday** [comment]
@kimmwest - It'd be great to get some of your thoughts on this at the next sprint meeting, to see whether it's meeting the needs you envisage or if there's anything obvious missing from the pages we've shown you so far.

**Comment by kimmwest** [comment]
Hi @stevenday - site admin seems really intuitive

Some comments:

If I want to download the CSV of e.g. all of the enablers and barriers - it would be good if in the CSV our contain some information about which study that relates to e.g. title or study reference. We would like this for impact information and  and study notes too 

When creating a new study and selecting PIs/research managers it would be good if they could be displayed in alphabetical order.  Research managers are only 4 people so would be good if we didn’t have to sift through entire list of users but this is a very minor issue.  

It would be useful if we could search/filter by study reference 

When creating a new study - what is the feedback and suggestions box for?  

Cheers

Kim

**Comment by stevenday** [comment]
@kimmwest - to address your comments:

> If I want to download the CSV of e.g. all of the enablers and barriers - it would be good if in the CSV our contain some information about which study that relates to e.g. title or study reference

The CSV downloads in the admin section are kind of a freebie, not part of the main CSV download feature we promised (That's now done, but I'll describe it in a separate ticket). I've created ticket #128 to track this request, but I'm not sure we'll have time to adjust these.

> When creating a new study and selecting PIs/research managers it would be good if they could be displayed in alphabetical order.  Research managers are only 4 people so would be good if we didn’t have to sift through entire list of users but this is a very minor issue.  

I've created #127 to track this.

> It would be useful if we could search/filter by study reference 
@BenJam already noticed this too, we've ticketed it at: https://github.com/mysociety/remit/issues/117

> When creating a new study - what is the feedback and suggestions box for?  

Hmm, you tell me! It was in the original schema as a field on studies, so I've created it thus. I had presumed it was somewhere you would record generic feedback that didn't fit into any of the more prescribed categories like enabler/barriers, but perhaps study notes already fulfil this role?

**Comment by kimmwest** [comment]
Haha whoops!  Sorry - my bad.   I think the study notes fulfil this role but I guess it doesn't hurt to leave it in.  Thanks, Steve

**Comment by stevenday** [comment]
All that's left of this is #117 now I think, so I'm going to close this ticket to keep things tidy.
