### ISSUE TITLE
User account management

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#9]
This ticket describes the various functionality that is necessary to support the fact that users of the site need to be uniquely identified and can personalise it to suit their needs.

### Anyone
- [x] Can register for an account on the site with an email address and password
- [x] Can log into their account with an email address and password
- [x] Can change their password
- [x] Can reset their password if they've forgotten it

## Questions

- ~~Do new users need to be approved by an admin before their account is activated? Or do we auto-approve foo@bar.msf.org users?~~ This has now been decided, and I've create #37 to represent that feature.

**Comment by stevenday** [comment]
All of these user stories are now complete and on the staging site for testing.

You access them via the "Sign In or Sign Up" link in the top right:

![screen shot 2016-01-14 at 13 39 18](https://cloud.githubusercontent.com/assets/663700/12325856/fedf722a-bac4-11e5-84cf-3a711f674d95.png)

Which then takes you to the login form, where you can either login in, or perform any of the other actions (signing up resetting your password, etc):

![screen shot 2016-01-14 at 13 39 28](https://cloud.githubusercontent.com/assets/663700/12325864/08707c44-bac5-11e5-8171-595635d37cc6.png)

Once you've logged in, you also get a new link in the main menu to change your account details:

![screen shot 2016-01-14 at 13 42 47](https://cloud.githubusercontent.com/assets/663700/12325833/ccaf7cf0-bac4-11e5-8ddb-0488927eb833.png)

Which gives you access to this page:

![screen shot 2016-01-14 at 13 42 55](https://cloud.githubusercontent.com/assets/663700/12325836/d6307d4c-bac4-11e5-9d3b-8a8bb1ac68d9.png)

Where you can change your password, email address or name.

There should be messages displayed to explain what's going on through each of these processes, but note especially that signing up and changing your email require you to click on a confirmation link that's emailed to you. These emails *might* arrive in your spam folder because this is just a staging site without everything set up as a production site would be, so do check there too.

I've already set up admin accounts for @zarino @BenJam @davea and Sarah and Kim from MSF, so you won't be able to register for new accounts with your usual email address. (I'll send the password details separately). If you want to test things easily, the best way is probably to use addresses like `your.name+1@example.com`, `your.name+2@example.com`, etc, since they will all go to `your.name@example.com` but they look different to the system.

Please comment here if there are any issues or queries, and we'll either fix them, or open new tickets to triage them and fix them later.

**Comment by kimmwest** [comment]
This looks good -  no issues from my side

**Comment by stevenday** [comment]
Thanks @kimmwest - I'll close this then
